### ISSUE TITLE
Docker-Compose healthcheck

### ISSUE THREAD

**Issue by LostOnTheLine** [nichobi/sponsorblockcast#29]
Just a note for a possible healthcheck. I'm not sure how well it does but it will check that go-chromecast is working at the very least

```yaml
version: '3.6'
services:
  sponsorblockcast:
    image: ghcr.io/nichobi/sponsorblockcast:latest
    network_mode: host
    environment:
      SBCPOLLINTERVAL: 1
      SBCSCANINTERVAL: 300
      SBCCATEGORIES: sponsor
      SBCDIR: /tmp/sponsorblockcast
    cap_add: 
      - NET_ADMIN
    restart: always
    healthcheck:
      test: ["CMD", "go-chromecast", "ls"]
      interval: 60s
      timeout: 10s
      retries: 3
```

I'm not sure what else to check for but that will verify the basics of the system are working
